name: example
description: Flutter example for wasm_ffi
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ffi: ^2.1.3
  web: ^1.0.0
  wasm_ffi:
    path: ../

dev_dependencies:
  ffigen: ^14.0.0
  lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/libWasmFfi.so