name: example
description: Vanilla Dart example for wasm_ffi
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  ffi: ^2.1.3
  web: ^1.0.0
  wasm_ffi:
    path: ../

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  ffigen: ^14.0.0
  lints: ^4.0.0
  test: ^1.24.0
