name: wasm_ffi
description: A wrapper for wasm which can be used as a drop-in replacement for dart:ffi for Web platform.
version: 1.0.1
repository: https://github.com/vm75/wasm_ffi/

environment:
  sdk: ^3.5.1

dependencies:
  ffi: ^2.1.3
  http: ^1.2.2
  meta: ^1.15.0
  path: ^1.9.0
  web: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

platforms:
  web:
