name: wasm_ffi
version: 0.7.4

repository: https://github.com/vm75/wasm_ffi/
description: Translates dart:ffi calls on the web to WebAssembly using dart:js

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  js: ^0.6.3
  meta: ^1.3.0
dev_dependencies:
  flutter_lints: ^2.0.1
