name: wasm_ffi
description: dart:ffi-like wrapper for wasm
version: 0.9.2
repository: https://github.com/vm75/wasm_ffi/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.1

platforms:
  web: