name: wasm_ffi
description: A wrapper for wasm which can be used as a drop-in replacement for dart:ffi for Web platform.
version: 0.9.4
repository: https://github.com/vm75/wasm_ffi/

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  inject_js: ^2.0.0
  js: ^0.6.7
  meta: ^1.3.0
  wasm_interop: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1

platforms:
  web:
