name: example
description: "A dart-web example for wasm_ffi"
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  web: ^1.0.0
  universal_ffi:
    path: ../

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^4.0.0
  ffigen: ^14.0.0
