name: wasm_ffi_example_flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  inject_js: ^2.0.0
  wasm_ffi:
    path: ..

flutter:
  assets:
    - assets/libopus.js
    - assets/libopus.wasm
