name: universal_ffi
description: A drop-in replacement for dart:ffi for all platforms.
version: 1.0.0
repository: https://github.com/vm75/native.ffi/tree/main/universal_ffi

environment:
  sdk: ^3.5.1

dependencies:
  ffi: ^2.1.3
  path: ^1.9.0
  wasm_ffi: ^2.0.0

dependency_overrides:
  wasm_ffi:
    path: ../wasm_ffi/

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
